#ifndef MYPAINTCONFIG_H
#define MYPAINTCONFIG_H

#ifndef MYPAINT_TILE_SIZE
#define MYPAINT_TILE_SIZE 64
#endif

#ifndef MYPAINT_NUM_CHANS
#define MYPAINT_NUM_CHANS 11
#endif

#ifndef MYPAINT_MAX_THREADS
#define MYPAINT_MAX_THREADS 32
#endif

#ifndef MYPAINT_MAX_MIPMAP_LEVEL
#define MYPAINT_MAX_MIPMAP_LEVEL 4
#endif

#ifndef MYPAINT_WGM_EPSILON
#define MYPAINT_WGM_EPSILON 0.001
#endif

#endif /* MYPAINTCONFIG_H */
